services:
  - type: web
    name: online-judge-platform
    env: node
    region: oregon
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    # Add your environment variables in Render dashboard:
    # MONGO_URI, JWT_SECRET, ADMIN_SECURITY_KEY
